# Configuration des performances pour le module DOM
parameters:
    # Cache des catégories DOM (en secondes)
    dom.cache.categories_lifetime: 1800  # 30 minutes
    dom.cache.sous_types_lifetime: 3600  # 1 heure
    dom.cache.rmq_lifetime: 3600         # 1 heure
    
    # Limites de requêtes
    dom.query.max_results: 1000
    dom.query.timeout: 30

services:
    # Service de cache DOM
    App\Service\Dom\DomCacheService:
        public: true
        arguments:
            $cache: '@cache.app'
            $em: '@doctrine.orm.entity_manager'
            $sousTypeDocumentRepository: '@App\Repository\Dom\DomSousTypeDocumentRepository'

    # Configuration des pools de cache pour DOM
    dom.cache_pool:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter
        arguments:
            - 0  # pas de limite de mémoire
            - true  # store serialized
        tags:
            - { name: 'cache.pool' }

when@prod:
    parameters:
        # Cache plus agressif en production
        dom.cache.categories_lifetime: 3600  # 1 heure
        dom.cache.sous_types_lifetime: 7200  # 2 heures
        dom.cache.rmq_lifetime: 7200         # 2 heures

    services:
        # Utiliser Redis en production si disponible
        dom.cache_pool:
            class: Symfony\Component\Cache\Adapter\RedisAdapter
            arguments:
                - '@Redis'
                - 'dom'
                - 0  # pas de limite de mémoire
            tags:
                - { name: 'cache.pool' }
